### ISSUE TITLE
Error: Cannot find module 'waterline-model-loader' 

### ISSUE THREAD

**Issue by jazlopez** [arjanfrans/waterline-model-loader#1]
Hello, anyone mantaining this repo?
I think the package is broken.  Basically I am not able to work with it at all.

Environment:

````shell
$ uname -a
Darwin Kernel Version 15.6.0: Fri Feb 17 10:21:18 PST 2017; root:xnu-3248.60.11.4.1~1/RELEASE_X86_64 x86_64

$ node -v
v6.9.1

$ npm -v
3.10.8
````

Steps to reproduce:

* After installing the package like so:

````
$ npm install waterline-model-loader --save 
````
And then in my index.js

````node
'use strict';
const modelLoader = require('waterline-model-loader').default;
````
Output:
````shell

module.js:471
    throw err;
    ^

Error: Cannot find module 'waterline-model-loader'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/index.js:14:54)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

Process finished with exit code 1
````

**Comment by arjanfrans** [comment]
I'll check it today.

**Comment by arjanfrans** [comment]
I forgot to add an .npmignore, so .gitignore was used which contained the /dist directory. Update to the package to the latest version (0.2.7).
